# Generated by Django 5.1.1 on 2024-10-09 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_memetemplate_user_is_subscribed_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain only letters, numbers and @/./+/-/_..', regex='^[\\w.@+-]+$')], verbose_name='Name user'),
        ),
    ]
